default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
  port: <%= Rails.application.credentials.dig(:db, :port) || 5432 %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>